### PR TITLE
	[Helper] Automatically configure the JSON builder

### PR DESCRIPTION
**Pull request by egeloen**
This PR fixes egeloen/IvoryGoogleMapBundle#183

### CODE REVIEW

**Comment by egeloen** [comment]
@markbijl This PR is for you. Can you confirm it fixes your issue when you find some time? :)

**Comment by aarsla** [comment]
Sorry, this does not work for me, polyline still has escaped `\\\\` characters.
It is the same wither with hardcoding constructor or changing AbstractHelperBuilder.php.

**Comment by egeloen** [comment]
Hum, good point, you're using the bundle so the builder is not used for creating the helpers... Let me try somethng after my workday.

**Comment by egeloen** [comment]
Closing as this is defintively not the right way to go...

**Pull request closed without merging**
